export const REGIONS = [
  { id: 'europe', label: 'Europe' },
  { id: 'indo-pacific', label: 'Indo-Pacific' },
  { id: 'middle-east', label: 'Middle East' },
  { id: 'africa', label: 'Africa' },
  { id: 'americas', label: 'Americas' },
]

/** @type {object[]} */
export const CANDIDATES = [
  {
    id: 'ramstein-ab',
    name: 'Ramstein Air Base',
    hostCountry: 'Germany',
    region: 'europe',
    lat: 49.4,
    lon: 7.6,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Air mobility and command hub',
    energy: 'Large campus. Rhineland-Palatinate heat market.',
    paUrl: 'https://www.ramstein.af.mil/',
    sources: ['Ramstein Air Base Public Affairs', 'CRS overseas basing materials'],
  },
  {
    id: 'spangdahlem-ab',
    name: 'Spangdahlem Air Base',
    hostCountry: 'Germany',
    region: 'europe',
    lat: 50.0,
    lon: 6.7,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Fighter wing',
    energy: 'Enduring garrison. Regional geothermal heat market.',
    paUrl: 'https://www.spangdahlem.af.mil/',
    sources: ['Spangdahlem Air Base Public Affairs'],
  },
  {
    id: 'usag-bavaria',
    name: 'U.S. Army Garrison Bavaria',
    hostCountry: 'Germany',
    region: 'europe',
    lat: 49.7,
    lon: 11.9,
    service: 'U.S. Army',
    command: 'USAREUR-AF',
    role: 'Grafenwoehr and Hohenfels training complex',
    energy: 'Sustained power and heat demand across a large training footprint.',
    paUrl: 'https://home.army.mil/bavaria',
    sources: ['U.S. Army Garrison Bavaria'],
  },
  {
    id: 'usag-stuttgart',
    name: 'U.S. Army Garrison Stuttgart',
    hostCountry: 'Germany',
    region: 'europe',
    lat: 48.7,
    lon: 9.1,
    service: 'U.S. Army',
    command: 'USAREUR-AF',
    role: 'Headquarters campus',
    energy: 'Headquarters campus energy demand.',
    paUrl: 'https://home.army.mil/stuttgart',
    sources: ['U.S. Army Garrison Stuttgart'],
  },
  {
    id: 'usag-wiesbaden',
    name: 'U.S. Army Garrison Wiesbaden',
    hostCountry: 'Germany',
    region: 'europe',
    lat: 50.0,
    lon: 8.3,
    service: 'U.S. Army',
    command: 'USAREUR-AF',
    role: 'Army headquarters campus',
    energy: 'Enduring garrison.',
    paUrl: 'https://home.army.mil/wiesbaden',
    sources: ['U.S. Army Garrison Wiesbaden'],
  },
  {
    id: 'raf-lakenheath',
    name: 'RAF Lakenheath',
    hostCountry: 'United Kingdom',
    region: 'europe',
    lat: 52.4,
    lon: 0.6,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Fighter wing at RAF station',
    energy: 'Dense air-wing operations.',
    paUrl: 'https://www.lakenheath.af.mil/',
    sources: ['RAF Lakenheath Public Affairs'],
  },
  {
    id: 'raf-mildenhall',
    name: 'RAF Mildenhall',
    hostCountry: 'United Kingdom',
    region: 'europe',
    lat: 52.4,
    lon: 0.5,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Air mobility and tanker',
    energy: 'Air mobility operations.',
    paUrl: 'https://www.mildenhall.af.mil/',
    sources: ['RAF Mildenhall Public Affairs'],
  },
  {
    id: 'aviano-ab',
    name: 'Aviano Air Base',
    hostCountry: 'Italy',
    region: 'europe',
    lat: 46.0,
    lon: 12.6,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Fighter wing, northern Italy',
    energy: 'Italy operates commercial geothermal power.',
    paUrl: 'https://www.aviano.af.mil/',
    sources: ['Aviano Air Base Public Affairs'],
  },
  {
    id: 'nas-sigonella',
    name: 'Naval Air Station Sigonella',
    hostCountry: 'Italy',
    region: 'europe',
    lat: 37.4,
    lon: 14.9,
    service: 'U.S. Navy',
    command: 'CNREURAFCENT',
    role: 'Air station, Sicily',
    energy: 'Mediterranean aviation and logistics hub.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/NAS-Sigonella/',
    sources: ['NAS Sigonella'],
  },
  {
    id: 'nsa-naples',
    name: 'Naval Support Activity Naples',
    hostCountry: 'Italy',
    region: 'europe',
    lat: 40.9,
    lon: 14.3,
    service: 'U.S. Navy',
    command: 'CNREURAFCENT',
    role: 'Navy support and headquarters',
    energy: 'Headquarters and support campus.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/NSA-Naples/',
    sources: ['NSA Naples'],
  },
  {
    id: 'ns-rota',
    name: 'Naval Station Rota',
    hostCountry: 'Spain',
    region: 'europe',
    lat: 36.6,
    lon: -6.3,
    service: 'U.S. Navy',
    command: 'CNREURAFCENT',
    role: 'Atlantic and Mediterranean logistics',
    energy: 'Waterfront and airfield operations.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/NS-Rota/',
    sources: ['Naval Station Rota'],
  },
  {
    id: 'moron-ab',
    name: 'Morón Air Base',
    hostCountry: 'Spain',
    region: 'europe',
    lat: 37.2,
    lon: -5.6,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Contingency and mobility support',
    energy: 'Air mobility operations.',
    paUrl: 'https://www.usafe.af.mil/',
    sources: ['USAF / Spanish host pages'],
  },
  {
    id: 'lajes-field',
    name: 'Lajes Field',
    hostCountry: 'Portugal',
    region: 'europe',
    lat: 38.8,
    lon: -27.1,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'Azores airfield access',
    energy: 'Azores volcanic province. Operating geothermal plants on São Miguel.',
    paUrl: 'https://www.lajes.af.mil/',
    sources: ['USAF / Portuguese host pages'],
  },
  {
    id: 'nsa-souda-bay',
    name: 'Naval Support Activity Souda Bay',
    hostCountry: 'Greece',
    region: 'europe',
    lat: 35.5,
    lon: 24.1,
    service: 'U.S. Navy',
    command: 'CNREURAFCENT',
    role: 'Crete naval and air support',
    energy: 'Support installation on Crete. National geothermal resource documentation.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/NSA-Souda-Bay/',
    sources: ['NSA Souda Bay'],
  },
  {
    id: 'mk-air-base',
    name: 'Mihail Kogălniceanu Air Base',
    hostCountry: 'Romania',
    region: 'europe',
    lat: 44.4,
    lon: 28.5,
    service: 'U.S. Army / U.S. Air Force',
    command: 'USAREUR-AF',
    role: 'Black Sea support hub',
    energy: 'Support and air mobility hub.',
    paUrl: 'https://www.eur.army.mil/',
    sources: ['USAREUR-AF / Romanian host materials'],
  },
  {
    id: 'incirlik-ab',
    name: 'Incirlik Air Base',
    hostCountry: 'Turkey',
    region: 'europe',
    lat: 37.0,
    lon: 35.4,
    service: 'U.S. Air Force',
    command: 'USAFE-AFAFRICA',
    role: 'USAF presence at Turkish air base',
    energy: 'Turkey is a large geothermal electricity producer.',
    paUrl: 'https://www.incirlik.af.mil/',
    sources: ['USAFE materials', 'Turkish energy statistics'],
  },
  {
    id: 'kadena-ab',
    name: 'Kadena Air Base',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 26.4,
    lon: 127.8,
    service: 'U.S. Air Force',
    command: 'PACAF / USFJ',
    role: 'Largest U.S. air base in the Pacific (USAF public materials)',
    energy: 'Large enduring installation. Host-nation commercial geothermal.',
    paUrl: 'https://www.kadena.af.mil/',
    sources: ['Kadena Air Base Public Affairs'],
  },
  {
    id: 'yokota-ab',
    name: 'Yokota Air Base',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 35.7,
    lon: 139.3,
    service: 'U.S. Air Force',
    command: 'PACAF / USFJ',
    role: 'Airlift hub, Kanto',
    energy: 'Dense regional presence near Tokyo.',
    paUrl: 'https://www.yokota.af.mil/',
    sources: ['Yokota Air Base Public Affairs'],
  },
  {
    id: 'misawa-ab',
    name: 'Misawa Air Base',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 40.7,
    lon: 141.4,
    service: 'U.S. Air Force',
    command: 'PACAF / USFJ',
    role: 'Northern Honshu fighter and joint presence',
    energy: 'Tohoku geothermal development history.',
    paUrl: 'https://www.misawa.af.mil/',
    sources: ['Misawa Air Base Public Affairs'],
  },
  {
    id: 'mcas-iwakuni',
    name: 'MCAS Iwakuni',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 34.1,
    lon: 132.2,
    service: 'U.S. Marine Corps',
    command: 'USFJ',
    role: 'Marine Corps air station',
    energy: 'Marine Corps air station.',
    paUrl: 'https://www.mcasiwakuni.marines.mil/',
    sources: ['MCAS Iwakuni'],
  },
  {
    id: 'cfay-yokosuka',
    name: 'Commander Fleet Activities Yokosuka',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 35.3,
    lon: 139.7,
    service: 'U.S. Navy',
    command: 'CNRJ / USFJ',
    role: 'Principal U.S. Navy fleet concentration in Japan',
    energy: 'Waterfront and fleet concentration.',
    paUrl: 'https://cnrj.cnic.navy.mil/Installations/CFA-Yokosuka/',
    sources: ['CFA Yokosuka'],
  },
  {
    id: 'cfas-sasebo',
    name: 'Commander Fleet Activities Sasebo',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 33.2,
    lon: 129.7,
    service: 'U.S. Navy',
    command: 'CNRJ / USFJ',
    role: 'Fleet activities, Kyushu',
    energy: 'Waterfront fleet activities.',
    paUrl: 'https://cnrj.cnic.navy.mil/Installations/CFA-Sasebo/',
    sources: ['CFA Sasebo'],
  },
  {
    id: 'camp-zama',
    name: 'Camp Zama',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 35.5,
    lon: 139.4,
    service: 'U.S. Army',
    command: 'USARJ / USFJ',
    role: 'U.S. Army Japan headquarters',
    energy: 'Army headquarters campus.',
    paUrl: 'https://www.usarj.army.mil/',
    sources: ['U.S. Army Japan'],
  },
  {
    id: 'camp-foster',
    name: 'Camp Foster',
    hostCountry: 'Japan',
    region: 'indo-pacific',
    lat: 26.3,
    lon: 127.8,
    service: 'U.S. Marine Corps',
    command: 'USFJ',
    role: 'Marine Corps Base Camp Smedley D. Butler, Okinawa',
    energy: 'Okinawa Marine Corps garrison.',
    paUrl: 'https://www.mcbbutler.marines.mil/',
    sources: ['USMC / USFJ'],
  },
  {
    id: 'camp-humphreys',
    name: 'Camp Humphreys',
    hostCountry: 'South Korea',
    region: 'indo-pacific',
    lat: 37.0,
    lon: 127.0,
    service: 'U.S. Army',
    command: 'USFK',
    role: 'Largest U.S. overseas Army garrison (USFK public materials)',
    energy: 'Very large enduring garrison.',
    paUrl: 'https://home.army.mil/humphreys',
    sources: ['U.S. Army Garrison Humphreys'],
  },
  {
    id: 'osan-ab',
    name: 'Osan Air Base',
    hostCountry: 'South Korea',
    region: 'indo-pacific',
    lat: 37.1,
    lon: 127.0,
    service: 'U.S. Air Force',
    command: 'PACAF / USFK',
    role: 'Fighter wing',
    energy: 'Major air base.',
    paUrl: 'https://www.osan.af.mil/',
    sources: ['Osan Air Base Public Affairs'],
  },
  {
    id: 'kunsan-ab',
    name: 'Kunsan Air Base',
    hostCountry: 'South Korea',
    region: 'indo-pacific',
    lat: 35.9,
    lon: 126.6,
    service: 'U.S. Air Force',
    command: 'PACAF / USFK',
    role: 'Fighter wing, west coast',
    energy: 'Fighter wing air base.',
    paUrl: 'https://www.kunsan.af.mil/',
    sources: ['Kunsan Air Base Public Affairs'],
  },
  {
    id: 'camp-casey',
    name: 'Camp Casey',
    hostCountry: 'South Korea',
    region: 'indo-pacific',
    lat: 37.9,
    lon: 127.1,
    service: 'U.S. Army',
    command: 'USFK',
    role: 'Army installation north of Seoul',
    energy: 'Army garrison.',
    paUrl: 'https://www.usfk.mil/',
    sources: ['USFK'],
  },
  {
    id: 'al-udeid-ab',
    name: 'Al Udeid Air Base',
    hostCountry: 'Qatar',
    region: 'middle-east',
    lat: 25.1,
    lon: 51.3,
    service: 'U.S. Air Force',
    command: 'AFCENT',
    role: 'Air and command presence',
    energy: 'High cooling demand.',
    paUrl: 'https://www.afcent.af.mil/',
    sources: ['USAF / host-nation materials'],
  },
  {
    id: 'nsa-bahrain',
    name: 'Naval Support Activity Bahrain',
    hostCountry: 'Bahrain',
    region: 'middle-east',
    lat: 26.2,
    lon: 50.6,
    service: 'U.S. Navy',
    command: 'NAVCENT / Fifth Fleet',
    role: 'Fifth Fleet support',
    energy: 'Headquarters and waterfront campus. High cooling demand.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/NSA-Bahrain/',
    sources: ['NSA Bahrain'],
  },
  {
    id: 'ali-al-salem-ab',
    name: 'Ali Al Salem Air Base',
    hostCountry: 'Kuwait',
    region: 'middle-east',
    lat: 29.3,
    lon: 47.5,
    service: 'U.S. Air Force',
    command: 'AFCENT',
    role: 'Air mobility and support',
    energy: 'Air mobility support. High cooling demand.',
    paUrl: 'https://www.afcent.af.mil/',
    sources: ['USAF / host materials'],
  },
  {
    id: 'camp-lemonnier',
    name: 'Camp Lemonnier',
    hostCountry: 'Djibouti',
    region: 'africa',
    lat: 11.5,
    lon: 43.1,
    service: 'U.S. Navy',
    command: 'AFRICOM',
    role: 'AFRICOM support installation',
    energy: 'East African Rift geothermal province. Enduring installation.',
    paUrl: 'https://cnreurafcent.cnic.navy.mil/Installations/Camp-Lemonnier-Djibouti/',
    sources: ['U.S. Navy / AFRICOM'],
  },
  {
    id: 'pituffik-sb',
    name: 'Pituffik Space Base',
    hostCountry: 'Greenland (Denmark)',
    region: 'americas',
    lat: 76.5,
    lon: -68.7,
    service: 'U.S. Space Force',
    command: 'USSF',
    role: 'Arctic space installation; formerly Thule Air Base',
    energy: 'Isolated Arctic logistics. On-site generation.',
    paUrl: 'https://www.petersonschriever.spaceforce.mil/Pituffik-SB-Greenland/',
    sources: ['Pituffik Space Base'],
  },
  {
    id: 'soto-cano-ab',
    name: 'Soto Cano Air Base',
    hostCountry: 'Honduras',
    region: 'americas',
    lat: 14.4,
    lon: -87.6,
    service: 'U.S. Air Force / U.S. Army',
    command: 'SOUTHCOM',
    role: 'Joint Task Force-Bravo support',
    energy: 'Honduras operates geothermal plants.',
    paUrl: 'https://www.jtfb.southcom.mil/',
    sources: ['USAF / SOUTHCOM'],
  },
  {
    id: 'guantanamo-nb',
    name: 'Naval Station Guantanamo Bay',
    hostCountry: 'Cuba',
    region: 'americas',
    lat: 19.9,
    lon: -75.2,
    service: 'U.S. Navy',
    command: 'CNRSE',
    role: 'U.S. Navy station',
    energy: 'Isolated on-base power system.',
    paUrl: 'https://cnrse.cnic.navy.mil/Installations/NS-Guantanamo-Bay/',
    sources: ['Naval Station Guantanamo Bay'],
  },
]

export function regionLabel(id) {
  return REGIONS.find((r) => r.id === id)?.label || id
}

export function hostCountries() {
  return [...new Set(CANDIDATES.map((c) => c.hostCountry))].sort((a, b) => a.localeCompare(b))
}

export function filterCandidates({ region = 'all', country = 'all', q = '' } = {}) {
  const query = q.trim().toLowerCase()
  return CANDIDATES.filter((c) => {
    if (region !== 'all' && c.region !== region) return false
    if (country !== 'all' && c.hostCountry !== country) return false
    if (query) {
      const hay = `${c.name} ${c.hostCountry} ${c.service} ${c.role} ${c.energy}`.toLowerCase()
      if (!hay.includes(query)) return false
    }
    return true
  })
}

export function inventoryStats() {
  const byRegion = {}
  const byCountry = {}
  for (const c of CANDIDATES) {
    byRegion[c.region] = (byRegion[c.region] || 0) + 1
    byCountry[c.hostCountry] = (byCountry[c.hostCountry] || 0) + 1
  }
  return {
    total: CANDIDATES.length,
    countries: Object.keys(byCountry).length,
    byRegion,
    byCountry,
  }
}
