/** Host countries with U.S. installations that lack a full geothermal market brief. */
export const HOST_MARKETS = [
  {
    id: 'bahrain',
    name: 'Bahrain',
    hostCountry: 'Bahrain',
    region: 'middle-east',
    image: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'The Electricity and Water Authority operates Bahrain’s power and water system.',
      'Naval Support Activity Bahrain supports U.S. Navy Fifth Fleet headquarters.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'cuba',
    name: 'Cuba',
    hostCountry: 'Cuba',
    region: 'americas',
    image: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Naval Station Guantanamo Bay is an isolated U.S. Navy station with an on-base power system.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'djibouti',
    name: 'Djibouti',
    hostCountry: 'Djibouti',
    region: 'africa',
    image: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Djibouti sits on the East African Rift. The national energy program includes geothermal exploration in the Asal-Ghoubbet rift.',
      'Camp Lemonnier is the named U.S. Navy-led AFRICOM support installation.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'germany',
    name: 'Germany',
    hostCountry: 'Germany',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Germany produces geothermal electricity and district heat under federal mining and renewable-energy law.',
      'U.S. Army and Air Force garrisons operate in Rhineland-Palatinate, Bavaria, Baden-Württemberg, and Hesse.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'greece',
    name: 'Greece',
    hostCountry: 'Greece',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Greece has documented high-enthalpy geothermal resources on several islands and in the north.',
      'Naval Support Activity Souda Bay is the U.S. Navy support location on Crete.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'greenland',
    name: 'Greenland',
    hostCountry: 'Greenland (Denmark)',
    region: 'americas',
    image: 'https://images.unsplash.com/photo-1483728642383-5c3a5a1e4e9b?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Greenland energy policy is administered in Nuuk. Isolated Arctic settlements run on imported fuel and local hydro where built.',
      'Pituffik Space Base is an isolated U.S. Space Force installation with extreme logistics.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'honduras',
    name: 'Honduras',
    hostCountry: 'Honduras',
    region: 'americas',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Honduras operates geothermal plants at Platanares and has a civil geothermal concession regime.',
      'Soto Cano Air Base supports Joint Task Force-Bravo.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'italy',
    name: 'Italy',
    hostCountry: 'Italy',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Italy operates commercial geothermal power in Tuscany. The Ministry of Environment and Energy Security administers energy policy.',
      'U.S. Air Force and Navy installations operate in the north, in Naples, and in Sicily.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'kuwait',
    name: 'Kuwait',
    hostCountry: 'Kuwait',
    region: 'middle-east',
    image: 'https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'The Ministry of Electricity, Water and Renewable Energy operates Kuwait’s power system.',
      'Ali Al Salem Air Base is the named air mobility and support location.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'portugal',
    name: 'Portugal',
    hostCountry: 'Portugal',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'The Azores are a volcanic province with operating geothermal plants on São Miguel.',
      'Lajes Field is U.S. airfield access in the mid-Atlantic.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'qatar',
    name: 'Qatar',
    hostCountry: 'Qatar',
    region: 'middle-east',
    image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Qatar’s energy program is built on natural gas and a growing solar fleet under the Ministry of State for Energy Affairs.',
      'Al Udeid Air Base is a major air and command location with high cooling demand.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'romania',
    name: 'Romania',
    hostCountry: 'Romania',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Romania produces heat from geothermal wells in the west.',
      'Mihail Kogălniceanu Air Base is the named Black Sea support hub in public materials.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'south-korea',
    name: 'South Korea',
    hostCountry: 'South Korea',
    region: 'asia-pacific',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'The Ministry of Trade, Industry and Energy administers Republic of Korea energy policy.',
      'Camp Humphreys, Osan Air Base, Kunsan Air Base, and Camp Casey are major U.S. installations.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'spain',
    name: 'Spain',
    hostCountry: 'Spain',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Spain administers electricity and heat policy through the Ministry for the Ecological Transition.',
      'Naval Station Rota and Morón Air Base are Atlantic and Mediterranean logistics nodes.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'turkey',
    name: 'Turkey',
    hostCountry: 'Turkey',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'Turkey is among the largest geothermal electricity producers. The Ministry of Energy and Natural Resources publishes capacity statistics.',
      'Incirlik Air Base is the named USAF presence at a Turkish air base.',
    ],
    analysis: [],
    docIds: [],
  },
  {
    id: 'united-kingdom',
    name: 'United Kingdom',
    hostCountry: 'United Kingdom',
    region: 'europe',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=80',
    status: 'published',
    hostProfile: true,
    applications: [],
    overview: [
      'The Department for Energy Security and Net Zero administers UK energy and heat policy.',
      'RAF Lakenheath and RAF Mildenhall are major U.S. Air Force installations in East Anglia.',
    ],
    analysis: [],
    docIds: [],
  },
]

export const HOST_NAME_BY_MARKET_ID = {
  'bahrain': 'Bahrain',
  'chile': 'Chile',
  'cuba': 'Cuba',
  'djibouti': 'Djibouti',
  'el-salvador': 'El Salvador',
  'germany': 'Germany',
  'greece': 'Greece',
  'greenland': 'Greenland (Denmark)',
  'honduras': 'Honduras',
  'indonesia': 'Indonesia',
  'italy': 'Italy',
  'japan': 'Japan',
  'kuwait': 'Kuwait',
  'mexico': 'Mexico',
  'new-zealand': 'New Zealand',
  'papua-new-guinea': 'Papua New Guinea',
  'philippines': 'Philippines',
  'portugal': 'Portugal',
  'qatar': 'Qatar',
  'romania': 'Romania',
  'south-korea': 'South Korea',
  'spain': 'Spain',
  'taiwan': 'Taiwan',
  'turkey': 'Turkey',
  'united-kingdom': 'United Kingdom',
}

/** Resolve CANDIDATES.hostCountry for a market id or record. */
export function hostNameForMarket(marketOrId) {
  const id = typeof marketOrId === 'string' ? marketOrId : marketOrId?.id
  if (!id) return null
  if (HOST_NAME_BY_MARKET_ID[id]) return HOST_NAME_BY_MARKET_ID[id]
  const market = typeof marketOrId === 'object' ? marketOrId : null
  if (market?.hostCountry) return market.hostCountry
  if (market?.name) {
    if (market.name === 'Greenland') return 'Greenland (Denmark)'
    return market.name
  }
  return null
}
